import express from 'express';
import db from'./db/index.js';
import dotenv from 'dotenv';
import cors from 'cors';
import bodyParser from'body-parser';
import cookieParser from 'cookie-parser';
import api from './api/api.js';
dotenv.config();
const app = express();
app.use(cors());
const PORT = process.env.PORT;
app.use(bodyParser.json({ extends : true}));
app.use(bodyParser.urlencoded({extended: true}));
app.use('/',api);
app.use(cookieParser());
db();
app.listen(PORT, () => {console.log(`localhost:${PORT}`)});