import express from 'express';
import { login,register } from '../auth/auth.controller.js';
import { saveCart } from '../cart/cart.controllers.js';
import { middlewareAuth } from '../middleware/middlewareAuth.js';
import { createProduct, deleteProduct, editProduct, getProduct, getProductByName, listProduct, searchProduct } from '../product/product.controller.js';
const api = express.Router();
 api.post('/auth',login);
 api.post('/auth/register',register);
api.get('/product/:name',middlewareAuth.verifyToken,getProductByName);
api.get('/product',middlewareAuth.verifyToken,listProduct);
api.post('/product',middlewareAuth.verifyToken,createProduct);
api.put('/product/:id',middlewareAuth.verifyToken,editProduct);
api.get('/product/:id',middlewareAuth.verifyToken,getProduct);
api.post('/product/search',middlewareAuth.verifyToken,searchProduct);
api.delete('/product/:id',middlewareAuth.verifyToken,deleteProduct);
api.post('/saveCart',middlewareAuth.verifyToken,saveCart);
export default api;