import express from 'express';
import { login,register } from '../auth/auth.controller.js';
import { saveCart } from '../cart/cart.controllers.js';
import { middlewareAuth } from '../middleware/middlewareAuth.js';
import { createProduct, deleteProduct, editProduct, getProduct, getProductByName, listProduct, searchProduct } from '../product/product.controller.js';
const api = express.Router();
 api.post('/auth',login);
 api.post('/auth/register',register);
api.get('/product/:name',middlewareAuth.verifyToken,getProductByName);
api.get('/product',listProduct);
api.post('/product',createProduct);
api.put('/product/:id',editProduct);
api.get('/product/:id',getProduct);
api.post('/product/search',searchProduct);
api.delete('/product/:id',deleteProduct);
api.post('/saveCart',saveCart);
export default api;